apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: repo-scanner-pdb
  namespace: repo-scanner
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: repo-scanner
      component: api